apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::315281578625:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-5CnlHqizzygY
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}

  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::315281578625:user/vinod
      username: vinod

kind: ConfigMap
metadata:
  creationTimestamp: "2026-07-05T04:29:24Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1154"
  uid: 97968302-c8be-493e-a743-b8f3444ecf02